import { useState, useEffect } from 'react';
import { ArrowRight, Eye } from 'lucide-react';
import clsx from 'clsx';

export type ReadingLevel = 'easy' | 'medium' | 'hard';

export interface ReadingItem {
  id: string;
  cyrillic: string;
  phonetic: string;
  translation: string;
}

export const READING_DATA: Record<ReadingLevel, ReadingItem[]> = {
  easy: [
    { id: 'e1', cyrillic: 'ДА', phonetic: 'DA', translation: 'Yes' },
    { id: 'e2', cyrillic: 'МА-МА', phonetic: 'MA-MA', translation: 'Mom' },
    { id: 'e3', cyrillic: 'ПА-ПА', phonetic: 'PA-PA', translation: 'Dad' },
    { id: 'e4', cyrillic: 'КОТ', phonetic: 'KOT', translation: 'Cat' },
    { id: 'e5', cyrillic: 'ДОМ', phonetic: 'DOM', translation: 'House' },
    { id: 'e6', cyrillic: 'СОК', phonetic: 'SOK', translation: 'Juice' },
    { id: 'e7', cyrillic: 'НОС', phonetic: 'NOS', translation: 'Nose' },
    { id: 'e8', cyrillic: 'ТА-МА', phonetic: 'TA-MA', translation: 'Tama (name)' },
    { id: 'e9', cyrillic: 'КА-ФЕ', phonetic: 'KA-FE', translation: 'Cafe' },
    { id: 'e10', cyrillic: 'СУП', phonetic: 'SOUP', translation: 'Soup' },
    { id: 'e11', cyrillic: 'СНЕГ', phonetic: 'SNEG', translation: 'Snow' },
    { id: 'e12', cyrillic: 'ХЛЕБ', phonetic: 'KHLEB', translation: 'Bread' },
    { id: 'e13', cyrillic: 'МЁД', phonetic: 'MYOD', translation: 'Honey' },
    { id: 'e14', cyrillic: 'ДЕНЬ', phonetic: 'DEN\'', translation: 'Day' },
    { id: 'e15', cyrillic: 'НОЧЬ', phonetic: 'NOCH\'', translation: 'Night' },
    { id: 'e16', cyrillic: 'РЫБА', phonetic: 'RYBA', translation: 'Fish' },
    { id: 'e17', cyrillic: 'УТРО', phonetic: 'UTRO', translation: 'Morning' },
    { id: 'e18', cyrillic: 'ЛЕТО', phonetic: 'LETO', translation: 'Summer' },
    { id: 'e19', cyrillic: 'ЗИМА', phonetic: 'ZIMA', translation: 'Winter' },
    { id: 'e20', cyrillic: 'НЕБО', phonetic: 'NEBO', translation: 'Sky' },
    { id: 'e21', cyrillic: 'МОРЕ', phonetic: 'MORE', translation: 'Sea' },
    { id: 'e22', cyrillic: 'РЕКА', phonetic: 'REKA', translation: 'River' },
    { id: 'e23', cyrillic: 'ПОЛЕ', phonetic: 'POLE', translation: 'Field' },
    { id: 'e24', cyrillic: 'ГОРА', phonetic: 'GORA', translation: 'Mountain' },
    { id: 'e25', cyrillic: 'СЕЛО', phonetic: 'SELO', translation: 'Village' },
    { id: 'e26', cyrillic: 'ПАРК', phonetic: 'PARK', translation: 'Park' },
    { id: 'e27', cyrillic: 'РУКА', phonetic: 'RUKA', translation: 'Hand / Arm' },
    { id: 'e28', cyrillic: 'НОГА', phonetic: 'NOGA', translation: 'Leg / Foot' },
    { id: 'e29', cyrillic: 'ГЛАЗ', phonetic: 'GLAZ', translation: 'Eye' },
    { id: 'e30', cyrillic: 'УХО', phonetic: 'UKHO', translation: 'Ear' },
    { id: 'e31', cyrillic: 'БРАТ', phonetic: 'BRAT', translation: 'Brother' },
    { id: 'e32', cyrillic: 'СЫН', phonetic: 'SYN', translation: 'Son' },
    { id: 'e33', cyrillic: 'ДОЧЬ', phonetic: 'DOCH\'', translation: 'Daughter' },
    { id: 'e34', cyrillic: 'БАБА', phonetic: 'BABA', translation: 'Grandma' },
    { id: 'e35', cyrillic: 'ДЕТИ', phonetic: 'DETI', translation: 'Children' },
    { id: 'e36', cyrillic: 'ДРУГ', phonetic: 'DRUG', translation: 'Friend' },
    { id: 'e37', cyrillic: 'ОКНО', phonetic: 'OKNO', translation: 'Window' },
    { id: 'e38', cyrillic: 'ДВЕРЬ', phonetic: 'DVER\'', translation: 'Door' },
    { id: 'e39', cyrillic: 'СТОЛ', phonetic: 'STOL', translation: 'Table' },
    { id: 'e40', cyrillic: 'СТУЛ', phonetic: 'STUL', translation: 'Chair' },
    { id: 'e41', cyrillic: 'КНИГА', phonetic: 'KNIGA', translation: 'Book' },
    { id: 'e42', cyrillic: 'РУЧКА', phonetic: 'RUCHKA', translation: 'Pen' },
    { id: 'e43', cyrillic: 'СУМКА', phonetic: 'SUMKA', translation: 'Bag' },
    { id: 'e44', cyrillic: 'ШАПКА', phonetic: 'SHAPKA', translation: 'Hat / Cap' },
    { id: 'e45', cyrillic: 'ШУБА', phonetic: 'SHUBA', translation: 'Fur coat' },
    { id: 'e46', cyrillic: 'ОБУВЬ', phonetic: 'OBUV\'', translation: 'Footwear' },
    { id: 'e47', cyrillic: 'ЧАСЫ', phonetic: 'CHASY', translation: 'Clock / Watch' },
    { id: 'e48', cyrillic: 'ЛОЖКА', phonetic: 'LOZHKA', translation: 'Spoon' },
    { id: 'e49', cyrillic: 'ВИЛКА', phonetic: 'VILKA', translation: 'Fork' },
    { id: 'e50', cyrillic: 'ЧАШКА', phonetic: 'CHASHKA', translation: 'Cup' },
    { id: 'e51', cyrillic: 'КАША', phonetic: 'KASHA', translation: 'Porridge' },
    { id: 'e52', cyrillic: 'МЯСО', phonetic: 'MYASO', translation: 'Meat' },
    { id: 'e53', cyrillic: 'ЯЙЦО', phonetic: 'YAYTSO', translation: 'Egg' },
    { id: 'e54', cyrillic: 'САХАР', phonetic: 'SAKHAR', translation: 'Sugar' },
    { id: 'e55', cyrillic: 'МЫЛО', phonetic: 'MYLO', translation: 'Soap' },
    { id: 'e56', cyrillic: 'КОФЕ', phonetic: 'KOFE', translation: 'Coffee' },
    { id: 'e57', cyrillic: 'РЫСЬ', phonetic: 'RYS\'', translation: 'Lynx' },
    { id: 'e58', cyrillic: 'ВОЛК', phonetic: 'VOLK', translation: 'Wolf' },
    { id: 'e59', cyrillic: 'ЛИСА', phonetic: 'LISA', translation: 'Fox' },
    { id: 'e60', cyrillic: 'СОВА', phonetic: 'SOVA', translation: 'Owl' },
    { id: 'e61', cyrillic: 'ЧАЙ', phonetic: 'CHAY', translation: 'Tea' },
    { id: 'e62', cyrillic: 'МИР', phonetic: 'MIR', translation: 'World / Peace' },
    { id: 'e63', cyrillic: 'ЛЕД', phonetic: 'LED', translation: 'Ice' },
    { id: 'e64', cyrillic: 'СЫР', phonetic: 'SYR', translation: 'Cheese' },
    { id: 'e65', cyrillic: 'ШАР', phonetic: 'SHAR', translation: 'Balloon / Sphere' },
    { id: 'e66', cyrillic: 'МЯЧ', phonetic: 'MYACH', translation: 'Ball' },
    { id: 'e67', cyrillic: 'САД', phonetic: 'SAD', translation: 'Garden' },
    { id: 'e68', cyrillic: 'ЛЕС', phonetic: 'LES', translation: 'Forest' },
    { id: 'e69', cyrillic: 'ЗУБ', phonetic: 'ZUB', translation: 'Tooth' },
    { id: 'e70', cyrillic: 'ДУБ', phonetic: 'DUB', translation: 'Oak' },
    { id: 'e71', cyrillic: 'ЛУК', phonetic: 'LUK', translation: 'Onion / Bow' },
    { id: 'e72', cyrillic: 'РОТ', phonetic: 'ROT', translation: 'Mouth' },
    { id: 'e73', cyrillic: 'НОЖ', phonetic: 'NOZH', translation: 'Knife' },
    { id: 'e74', cyrillic: 'СОН', phonetic: 'SON', translation: 'Dream / Sleep' },
    { id: 'e75', cyrillic: 'ТОК', phonetic: 'TOK', translation: 'Current' },
    { id: 'e76', cyrillic: 'КОД', phonetic: 'KOD', translation: 'Code' },
    { id: 'e77', cyrillic: 'БАК', phonetic: 'BAK', translation: 'Tank' },
    { id: 'e78', cyrillic: 'МАК', phonetic: 'MAK', translation: 'Poppy' },
    { id: 'e79', cyrillic: 'ЛАК', phonetic: 'LAK', translation: 'Lacquer' },
    { id: 'e80', cyrillic: 'РАК', phonetic: 'RAK', translation: 'Crayfish' },
    { id: 'e81', cyrillic: 'ТАК', phonetic: 'TAK', translation: 'So / Thus' },
    { id: 'e82', cyrillic: 'ЧАС', phonetic: 'CHAS', translation: 'Hour' },
    { id: 'e83', cyrillic: 'ШАГ', phonetic: 'SHAG', translation: 'Step' },
    { id: 'e84', cyrillic: 'БОЙ', phonetic: 'BOY', translation: 'Battle' },
    { id: 'e85', cyrillic: 'МАЙ', phonetic: 'MAY', translation: 'May' },
    { id: 'e86', cyrillic: 'РАЙ', phonetic: 'RAY', translation: 'Paradise' },
    { id: 'e87', cyrillic: 'ГОД', phonetic: 'GOD', translation: 'Year' },
    { id: 'e88', cyrillic: 'РОД', phonetic: 'ROD', translation: 'Kind / Gender' },
    { id: 'e89', cyrillic: 'СОЛЬ', phonetic: 'SOL\'', translation: 'Salt' },
    { id: 'e90', cyrillic: 'БОЛЬ', phonetic: 'BOL\'', translation: 'Pain' },
    { id: 'e91', cyrillic: 'РОЛЬ', phonetic: 'ROL\'', translation: 'Role' },
    { id: 'e92', cyrillic: 'ТЕМ', phonetic: 'TEM', translation: 'By that' },
    { id: 'e93', cyrillic: 'ТОМ', phonetic: 'TOM', translation: 'Volume' },
    { id: 'e94', cyrillic: 'КОМ', phonetic: 'KOM', translation: 'Lump' },
    { id: 'e95', cyrillic: 'ДЕД', phonetic: 'DED', translation: 'Grandpa' },
    { id: 'e96', cyrillic: 'ЛУЧ', phonetic: 'LUCH', translation: 'Ray' },
    { id: 'e97', cyrillic: 'МЕЧ', phonetic: 'MECH', translation: 'Sword' },
    { id: 'e98', cyrillic: 'ПЕЧЬ', phonetic: 'PECH\'', translation: 'Oven' },
    { id: 'e99', cyrillic: 'РЕЧЬ', phonetic: 'RECH\'', translation: 'Speech' },
    { id: 'e100', cyrillic: 'ВЕС', phonetic: 'VES', translation: 'Weight' },
    // 100 NEW EASY EXAMPLES (e101 - e200)
    { id: 'e101', cyrillic: 'БОР', phonetic: 'BOR', translation: 'Pine forest' },
    { id: 'e102', cyrillic: 'ПАР', phonetic: 'PAR', translation: 'Steam' },
    { id: 'e103', cyrillic: 'ЖАР', phonetic: 'ZHAR', translation: 'Heat / Fever' },
    { id: 'e104', cyrillic: 'ДЫМ', phonetic: 'DYM', translation: 'Smoke' },
    { id: 'e105', cyrillic: 'ЛУГ', phonetic: 'LUG', translation: 'Meadow' },
    { id: 'e106', cyrillic: 'МОСТ', phonetic: 'MOST', translation: 'Bridge' },
    { id: 'e107', cyrillic: 'КУСТ', phonetic: 'KUST', translation: 'Bush' },
    { id: 'e108', cyrillic: 'ЛИСТ', phonetic: 'LIST', translation: 'Leaf / Sheet' },
    { id: 'e109', cyrillic: 'КРЕСТ', phonetic: 'KREST', translation: 'Cross' },
    { id: 'e110', cyrillic: 'ХВОСТ', phonetic: 'KHVOST', translation: 'Tail' },
    { id: 'e111', cyrillic: 'ХОЛМ', phonetic: 'KHOLM', translation: 'Hill' },
    { id: 'e112', cyrillic: 'ГРАД', phonetic: 'GRAD', translation: 'Hail / City' },
    { id: 'e113', cyrillic: 'ГРОМ', phonetic: 'GROM', translation: 'Thunder' },
    { id: 'e114', cyrillic: 'КРАЙ', phonetic: 'KRAY', translation: 'Edge / Region' },
    { id: 'e115', cyrillic: 'КЛЮЧ', phonetic: 'KLYUCH', translation: 'Key / Spring' },
    { id: 'e116', cyrillic: 'ГРАЧ', phonetic: 'GRACH', translation: 'Rook' },
    { id: 'e117', cyrillic: 'КРИК', phonetic: 'KRIK', translation: 'Shout / Cry' },
    { id: 'e118', cyrillic: 'СМЕХ', phonetic: 'SMEKH', translation: 'Laughter' },
    { id: 'e119', cyrillic: 'ГРЕХ', phonetic: 'GREKH', translation: 'Sin' },
    { id: 'e120', cyrillic: 'ПЛУГ', phonetic: 'PLUG', translation: 'Plow' },
    { id: 'e121', cyrillic: 'СНОП', phonetic: 'SNOP', translation: 'Sheaf' },
    { id: 'e122', cyrillic: 'СЛЕД', phonetic: 'SLED', translation: 'Track / Footprint' },
    { id: 'e123', cyrillic: 'ЗВОН', phonetic: 'ZVON', translation: 'Chime' },
    { id: 'e124', cyrillic: 'КЛОН', phonetic: 'KLON', translation: 'Clone' },
    { id: 'e125', cyrillic: 'ЗВЕРЬ', phonetic: 'ZVER\'', translation: 'Beast' },
    { id: 'e126', cyrillic: 'ДВОР', phonetic: 'DVOR', translation: 'Yard / Courtyard' },
    { id: 'e127', cyrillic: 'ВОР', phonetic: 'VOR', translation: 'Thief' },
    { id: 'e128', cyrillic: 'СОР', phonetic: 'SOR', translation: 'Trash' },
    { id: 'e129', cyrillic: 'СПОРТ', phonetic: 'SPORT', translation: 'Sport' },
    { id: 'e130', cyrillic: 'БОРЩ', phonetic: 'BORSCH', translation: 'Borscht' },
    { id: 'e131', cyrillic: 'КИТ', phonetic: 'KIT', translation: 'Whale' },
    { id: 'e132', cyrillic: 'КОНЬ', phonetic: 'KON\'', translation: 'Horse' },
    { id: 'e133', cyrillic: 'ТЕНЬ', phonetic: 'TEN\'', translation: 'Shadow' },
    { id: 'e134', cyrillic: 'ПЕНЬ', phonetic: 'PEN\'', translation: 'Stump' },
    { id: 'e135', cyrillic: 'ЛЕНЬ', phonetic: 'LEN\'', translation: 'Laziness' },
    { id: 'e136', cyrillic: 'ОГОНЬ', phonetic: 'OGON\'', translation: 'Fire' },
    { id: 'e137', cyrillic: 'УГОЛЬ', phonetic: 'UGOL\'', translation: 'Coal' },
    { id: 'e138', cyrillic: 'МЫШЬ', phonetic: 'MYSH\'', translation: 'Mouse' },
    { id: 'e139', cyrillic: 'ТИШЬ', phonetic: 'TISH\'', translation: 'Quiet' },
    { id: 'e140', cyrillic: 'ТУЧА', phonetic: 'TUCHA', translation: 'Cloud' },
    { id: 'e141', cyrillic: 'ДАЧА', phonetic: 'DACHA', translation: 'Summer house' },
    { id: 'e142', cyrillic: 'ЧАЩА', phonetic: 'CHASHCHA', translation: 'Thicket' },
    { id: 'e143', cyrillic: 'РОЩА', phonetic: 'ROSHCHA', translation: 'Grove' },
    { id: 'e144', cyrillic: 'КОЖА', phonetic: 'KOZHA', translation: 'Skin / Leather' },
    { id: 'e145', cyrillic: 'ЛУЖА', phonetic: 'LUZHA', translation: 'Puddle' },
    { id: 'e146', cyrillic: 'СТУЖА', phonetic: 'STUZHA', translation: 'Severe cold' },
    { id: 'e147', cyrillic: 'ДУША', phonetic: 'DUSHA', translation: 'Soul' },
    { id: 'e148', cyrillic: 'КИТАЙ', phonetic: 'KITAY', translation: 'China' },
    { id: 'e149', cyrillic: 'АЗИЯ', phonetic: 'AZIYA', translation: 'Asia' },
    { id: 'e150', cyrillic: 'ЗОНА', phonetic: 'ZONA', translation: 'Zone' },
    { id: 'e151', cyrillic: 'РОЗА', phonetic: 'ROZA', translation: 'Rose' },
    { id: 'e152', cyrillic: 'ВАЗА', phonetic: 'VAZA', translation: 'Vase' },
    { id: 'e153', cyrillic: 'КОЗА', phonetic: 'KOZA', translation: 'Goat' },
    { id: 'e154', cyrillic: 'ЛОЗА', phonetic: 'LOZA', translation: 'Vine' },
    { id: 'e155', cyrillic: 'СЛЕЗА', phonetic: 'SLEZA', translation: 'Tear' },
    { id: 'e156', cyrillic: 'БЕРЕЗА', phonetic: 'BEREZA', translation: 'Birch tree' },
    { id: 'e157', cyrillic: 'ТРАВА', phonetic: 'TRAVA', translation: 'Grass' },
    { id: 'e158', cyrillic: 'ДРОВА', phonetic: 'DROVA', translation: 'Firewood' },
    { id: 'e159', cyrillic: 'СЛАВА', phonetic: 'SLAVA', translation: 'Glory' },
    { id: 'e160', cyrillic: 'ГЛАВА', phonetic: 'GLAVA', translation: 'Chapter' },
    { id: 'e161', cyrillic: 'ТЬМА', phonetic: 'T\'MA', translation: 'Darkness' },
    { id: 'e162', cyrillic: 'ДОМА', phonetic: 'DOMA', translation: 'At home' },
    { id: 'e163', cyrillic: 'ТЕМА', phonetic: 'TEMA', translation: 'Topic' },
    { id: 'e164', cyrillic: 'СХЕМА', phonetic: 'SKHEMA', translation: 'Diagram' },
    { id: 'e165', cyrillic: 'ПОЭМА', phonetic: 'POEMA', translation: 'Poem' },
    { id: 'e166', cyrillic: 'СИСТЕМА', phonetic: 'SISTEMA', translation: 'System' },
    { id: 'e167', cyrillic: 'ПЛАНЕТА', phonetic: 'PLANETA', translation: 'Planet' },
    { id: 'e168', cyrillic: 'КОМЕТА', phonetic: 'KOMETA', translation: 'Comet' },
    { id: 'e169', cyrillic: 'РАКЕТА', phonetic: 'RAKETA', translation: 'Rocket' },
    { id: 'e170', cyrillic: 'КАРТА', phonetic: 'KARTA', translation: 'Map' },
    { id: 'e171', cyrillic: 'ПАРТА', phonetic: 'PARTA', translation: 'Desk' },
    { id: 'e172', cyrillic: 'МАРТ', phonetic: 'MART', translation: 'March' },
    { id: 'e173', cyrillic: 'АПРЕЛЬ', phonetic: 'APREL\'', translation: 'April' },
    { id: 'e174', cyrillic: 'ИЮНЬ', phonetic: 'IYUN\'', translation: 'June' },
    { id: 'e175', cyrillic: 'ИЮЛЬ', phonetic: 'IYUL\'', translation: 'July' },
    { id: 'e176', cyrillic: 'АВГУСТ', phonetic: 'AVGUST', translation: 'August' },
    { id: 'e177', cyrillic: 'СВЕТ', phonetic: 'SVET', translation: 'Light' },
    { id: 'e178', cyrillic: 'ЦВЕТ', phonetic: 'TSVET', translation: 'Color' },
    { id: 'e179', cyrillic: 'ОТВЕТ', phonetic: 'OTVET', translation: 'Answer' },
    { id: 'e180', cyrillic: 'СОВЕТ', phonetic: 'SOVET', translation: 'Advice' },
    { id: 'e181', cyrillic: 'ОБЕД', phonetic: 'OBED', translation: 'Lunch' },
    { id: 'e182', cyrillic: 'СОСЕД', phonetic: 'SOSED', translation: 'Neighbor' },
    { id: 'e183', cyrillic: 'ОБЕД', phonetic: 'OBED', translation: 'Meal' },
    { id: 'e184', cyrillic: 'ПАРА', phonetic: 'PARA', translation: 'Pair' },
    { id: 'e185', cyrillic: 'ФАРА', phonetic: 'FARA', translation: 'Headlight' },
    { id: 'e186', cyrillic: 'ТАРА', phonetic: 'TARA', translation: 'Packaging' },
    { id: 'e187', cyrillic: 'КАРА', phonetic: 'KARA', translation: 'Punishment' },
    { id: 'e188', cyrillic: 'МА-ЛО', phonetic: 'MA-LO', translation: 'Little' },
    { id: 'e189', cyrillic: 'МНО-ГО', phonetic: 'MNO-GO', translation: 'Much' },
    { id: 'e190', cyrillic: 'РА-НО', phonetic: 'RA-NO', translation: 'Early' },
    { id: 'e191', cyrillic: 'ПОЗД-НО', phonetic: 'POZD-NO', translation: 'Late' },
    { id: 'e192', cyrillic: 'ТЕМ-НО', phonetic: 'TEM-NO', translation: 'Dark' },
    { id: 'e193', cyrillic: 'ТЕП-ЛО', phonetic: 'TEP-LO', translation: 'Warm' },
    { id: 'e194', cyrillic: 'ХО-ЛОД', phonetic: 'KHO-LOD', translation: 'Cold' },
    { id: 'e195', cyrillic: 'ЖА-РА', phonetic: 'ZHA-RA', translation: 'Heat' },
    { id: 'e196', cyrillic: 'ТЫ', phonetic: 'TY', translation: 'You' },
    { id: 'e197', cyrillic: 'ОН', phonetic: 'ON', translation: 'He' },
    { id: 'e198', cyrillic: 'О-НА', phonetic: 'O-NA', translation: 'She' },
    { id: 'e199', cyrillic: 'О-НО', phonetic: 'O-NO', translation: 'It' },
    { id: 'e200', cyrillic: 'О-НИ', phonetic: 'O-NI', translation: 'They' }
  ],
  medium: [
    { id: 'm1', cyrillic: 'ВО-ДА', phonetic: 'VO-DA', translation: 'Water' },
    { id: 'm2', cyrillic: 'ГО-РОД', phonetic: 'GO-ROD', translation: 'City' },
    { id: 'm3', cyrillic: 'АП-ТЕ-КА', phonetic: 'AP-TE-KA', translation: 'Pharmacy' },
    { id: 'm4', cyrillic: 'ШКО-ЛА', phonetic: 'SHKO-LA', translation: 'School' },
    { id: 'm5', cyrillic: 'МО-ЛО-КО', phonetic: 'MO-LO-KO', translation: 'Milk' },
    { id: 'm6', cyrillic: 'ПАРК', phonetic: 'PARK', translation: 'Park' },
    { id: 'm7', cyrillic: 'ЛИ-МОН', phonetic: 'LI-MON', translation: 'Lemon' },
    { id: 'm8', cyrillic: 'СОЛН-ЦЕ', phonetic: 'SOLN-TSE', translation: 'Sun' },
    { id: 'm9', cyrillic: 'РЕ-КА', phonetic: 'RE-KA', translation: 'River' },
    { id: 'm10', cyrillic: 'ОК-НО', phonetic: 'OK-NO', translation: 'Window' },
    { id: 'm11', cyrillic: 'БА-НАН', phonetic: 'BA-NAN', translation: 'Banana' },
    { id: 'm12', cyrillic: 'ПИ-ЦЦА', phonetic: 'PIT-SA', translation: 'Pizza' },
    { id: 'm13', cyrillic: 'ЛАМ-ПА', phonetic: 'LAM-PA', translation: 'Lamp' },
    { id: 'm14', cyrillic: 'ПО-ЕЗД', phonetic: 'PO-YEZD', translation: 'Train' },
    { id: 'm15', cyrillic: 'ЛОД-КА', phonetic: 'LOD-KA', translation: 'Boat' },
    { id: 'm16', cyrillic: 'РЫ-БА', phonetic: 'RY-BA', translation: 'Fish' },
    { id: 'm17', cyrillic: 'МУ-ЗЫ-КА', phonetic: 'MU-ZY-KA', translation: 'Music' },
    { id: 'm18', cyrillic: 'ПИ-СЬ-МО', phonetic: 'PIS\'-MO', translation: 'Letter' },
    { id: 'm19', cyrillic: 'КНИ-ГА', phonetic: 'KNI-GA', translation: 'Book' },
    { id: 'm20', cyrillic: 'РУЧ-КА', phonetic: 'RUCH-KA', translation: 'Pen' },
    { id: 'm21', cyrillic: 'СУМ-КА', phonetic: 'SUM-KA', translation: 'Bag' },
    { id: 'm22', cyrillic: 'ШАП-КА', phonetic: 'SHAP-KA', translation: 'Hat' },
    { id: 'm23', cyrillic: 'НО-СОК', phonetic: 'NO-SOK', translation: 'Sock' },
    { id: 'm24', cyrillic: 'О-БУВЬ', phonetic: 'O-BUV\'', translation: 'Footwear' },
    { id: 'm25', cyrillic: 'ДВЕРЬ', phonetic: 'DVER\'', translation: 'Door' },
    { id: 'm26', cyrillic: 'СТЕН-КА', phonetic: 'STEN-KA', translation: 'Wall' },
    { id: 'm27', cyrillic: 'СТОЛ', phonetic: 'STOL', translation: 'Table' },
    { id: 'm28', cyrillic: 'СТУЛ', phonetic: 'STUL', translation: 'Chair' },
    { id: 'm29', cyrillic: 'ЛОЖ-КА', phonetic: 'LOSH-KA', translation: 'Spoon' },
    { id: 'm30', cyrillic: 'ВИЛ-КА', phonetic: 'VIL-KA', translation: 'Fork' },
    { id: 'm31', cyrillic: 'ЧАШ-КА', phonetic: 'CHASH-KA', translation: 'Cup' },
    { id: 'm32', cyrillic: 'МАС-ЛО', phonetic: 'MAS-LO', translation: 'Butter / Oil' },
    { id: 'm33', cyrillic: 'ХЛЕБ', phonetic: 'KHLEB', translation: 'Bread' },
    { id: 'm34', cyrillic: 'МЯ-СО', phonetic: 'MYA-SO', translation: 'Meat' },
    { id: 'm35', cyrillic: 'РИС', phonetic: 'RIS', translation: 'Rice' },
    { id: 'm36', cyrillic: 'СА-ХАР', phonetic: 'SA-KHAR', translation: 'Sugar' },
    { id: 'm37', cyrillic: 'О-ГУ-РЕЦ', phonetic: 'O-GU-RETS', translation: 'Cucumber' },
    { id: 'm38', cyrillic: 'ТО-МАТ', phonetic: 'TO-MAT', translation: 'Tomato' },
    { id: 'm39', cyrillic: 'ГРИБ', phonetic: 'GRIB', translation: 'Mushroom' },
    { id: 'm40', cyrillic: 'ЯБ-ЛО-КО', phonetic: 'YAB-LO-KO', translation: 'Apple' },
    { id: 'm41', cyrillic: 'ГРУ-ША', phonetic: 'GRU-SHA', translation: 'Pear' },
    { id: 'm42', cyrillic: 'СЛИ-ВА', phonetic: 'SLI-VA', translation: 'Plum' },
    { id: 'm43', cyrillic: 'А-ПЕЛЬ-СИН', phonetic: 'A-PEL\'-SIN', translation: 'Orange' },
    { id: 'm44', cyrillic: 'МЕ-ДОК', phonetic: 'ME-DOK', translation: 'Honey' },
    { id: 'm45', cyrillic: 'ТОРТ', phonetic: 'TORT', translation: 'Cake' },
    { id: 'm46', cyrillic: 'КЕКС', phonetic: 'KEKS', translation: 'Muffin' },
    { id: 'm47', cyrillic: 'ПИ-РОГ', phonetic: 'PI-ROG', translation: 'Pie' },
    { id: 'm48', cyrillic: 'КО-ФЕ', phonetic: 'KO-FE', translation: 'Coffee' },
    { id: 'm49', cyrillic: 'ЧАЙ-НИК', phonetic: 'CHAY-NIK', translation: 'Teapot' },
    { id: 'm50', cyrillic: 'ПУТЬ', phonetic: 'PUT\'', translation: 'Path / Way' },
    { id: 'm51', cyrillic: 'ЗИ-МА', phonetic: 'ZI-MA', translation: 'Winter' },
    { id: 'm52', cyrillic: 'ВЕС-НА', phonetic: 'VES-NA', translation: 'Spring' },
    { id: 'm53', cyrillic: 'ЛЕ-ТО', phonetic: 'LE-TO', translation: 'Summer' },
    { id: 'm54', cyrillic: 'О-СЕНЬ', phonetic: 'O-SEN\'', translation: 'Autumn' },
    { id: 'm55', cyrillic: 'У-ТРО', phonetic: 'U-TRO', translation: 'Morning' },
    { id: 'm56', cyrillic: 'ДЕНЬ', phonetic: 'DEN\'', translation: 'Day' },
    { id: 'm57', cyrillic: 'ВЕ-ЧЕР', phonetic: 'VE-CHER', translation: 'Evening' },
    { id: 'm58', cyrillic: 'НОЧЬ', phonetic: 'NOCH\'', translation: 'Night' },
    { id: 'm59', cyrillic: 'ВЕ-ТЕР', phonetic: 'VE-TER', translation: 'Wind' },
    { id: 'm60', cyrillic: 'ДОЖДЬ', phonetic: 'DOSHD\'', translation: 'Rain' },
    { id: 'm61', cyrillic: 'СНЕГ', phonetic: 'SNEG', translation: 'Snow' },
    { id: 'm62', cyrillic: 'ГРО-ЗА', phonetic: 'GRO-ZA', translation: 'Storm' },
    { id: 'm63', cyrillic: 'НЕ-БО', phonetic: 'NE-BO', translation: 'Sky' },
    { id: 'm64', cyrillic: 'ЛУ-НА', phonetic: 'LU-NA', translation: 'Moon' },
    { id: 'm65', cyrillic: 'ЗВЕЗ-ДА', phonetic: 'ZVEZ-DA', translation: 'Star' },
    { id: 'm66', cyrillic: 'МЕ-СЯЦ', phonetic: 'ME-SYATS', translation: 'Month' },
    { id: 'm67', cyrillic: 'ЧА-СЫ', phonetic: 'CHA-SY', translation: 'Clock / Watch' },
    { id: 'm68', cyrillic: 'КИ-НО', phonetic: 'KI-NO', translation: 'Cinema' },
    { id: 'm69', cyrillic: 'ТЕ-АТР', phonetic: 'TE-ATR', translation: 'Theater' },
    { id: 'm70', cyrillic: 'МУ-ЗЕЙ', phonetic: 'MU-ZEY', translation: 'Museum' },
    { id: 'm71', cyrillic: 'КАС-СА', phonetic: 'KAS-SA', translation: 'Cashier' },
    { id: 'm72', cyrillic: 'ЦЕ-НА', phonetic: 'TSE-NA', translation: 'Price' },
    { id: 'm73', cyrillic: 'КАР-ТА', phonetic: 'KAR-TA', translation: 'Map / Card' },
    { id: 'm74', cyrillic: 'ПОРТ', phonetic: 'PORT', translation: 'Port' },
    { id: 'm75', cyrillic: 'МЕ-ТРО', phonetic: 'ME-TRO', translation: 'Subway' },
    { id: 'm76', cyrillic: 'ТАК-СИ', phonetic: 'TAK-SI', translation: 'Taxi' },
    { id: 'm77', cyrillic: 'АВ-ТО-БУС', phonetic: 'AV-TO-BUS', translation: 'Bus' },
    { id: 'm78', cyrillic: 'БИ-ЛЕТ', phonetic: 'BI-LET', translation: 'Ticket' },
    { id: 'm79', cyrillic: 'ЗА-ВОД', phonetic: 'ZA-VOD', translation: 'Factory' },
    { id: 'm80', cyrillic: 'ПО-ЛЕ', phonetic: 'PO-LE', translation: 'Field' },
    { id: 'm81', cyrillic: 'МЕ-СТО', phonetic: 'ME-STO', translation: 'Place' },
    { id: 'm82', cyrillic: 'СЛО-ВО', phonetic: 'SLO-VO', translation: 'Word' },
    { id: 'm83', cyrillic: 'ГО-ЛОС', phonetic: 'GO-LOS', translation: 'Voice' },
    { id: 'm84', cyrillic: 'ГЛАЗ', phonetic: 'GLAZ', translation: 'Eye' },
    { id: 'm85', cyrillic: 'У-ХО', phonetic: 'U-KHO', translation: 'Ear' },
    { id: 'm86', cyrillic: 'РУ-КА', phonetic: 'RU-KA', translation: 'Hand / Arm' },
    { id: 'm87', cyrillic: 'НО-ГА', phonetic: 'NO-GA', translation: 'Leg / Foot' },
    { id: 'm88', cyrillic: 'ЛИ-ЦО', phonetic: 'LI-TSO', translation: 'Face' },
    { id: 'm89', cyrillic: 'Я-ЗЫК', phonetic: 'YA-ZYK', translation: 'Language / Tongue' },
    { id: 'm90', cyrillic: 'ПЕ-СНЯ', phonetic: 'PE-SNYA', translation: 'Song' },
    { id: 'm91', cyrillic: 'ТА-НЕЦ', phonetic: 'TA-NETS', translation: 'Dance' },
    { id: 'm92', cyrillic: 'И-ГРА', phonetic: 'I-GRA', translation: 'Game' },
    { id: 'm93', cyrillic: 'ДРУГ', phonetic: 'DRUG', translation: 'Friend' },
    { id: 'm94', cyrillic: 'БРАТ', phonetic: 'BRAT', translation: 'Brother' },
    { id: 'm95', cyrillic: 'СЕ-СТРА', phonetic: 'SE-STRA', translation: 'Sister' },
    { id: 'm96', cyrillic: 'ДЯ-ДЯ', phonetic: 'DYA-DYA', translation: 'Uncle' },
    { id: 'm97', cyrillic: 'ТЁ-ТЯ', phonetic: 'TYO-TYA', translation: 'Aunt' },
    { id: 'm98', cyrillic: 'О-ТЕЦ', phonetic: 'O-TETS', translation: 'Father' },
    { id: 'm99', cyrillic: 'МА-ТЬ', phonetic: 'MAT\'', translation: 'Mother' },
    { id: 'm100', cyrillic: 'СЫН', phonetic: 'SYN', translation: 'Son' },
    // 100 NEW MEDIUM EXAMPLES (m101 - m200)
    { id: 'm101', cyrillic: 'ПО-ГО-ДА', phonetic: 'PO-GO-DA', translation: 'Weather' },
    { id: 'm102', cyrillic: 'ПРИ-РО-ДА', phonetic: 'PRI-RO-DA', translation: 'Nature' },
    { id: 'm103', cyrillic: 'СВО-БО-ДА', phonetic: 'SVO-BO-DA', translation: 'Freedom' },
    { id: 'm104', cyrillic: 'ПО-БЕ-ДА', phonetic: 'PO-BE-DA', translation: 'Victory' },
    { id: 'm105', cyrillic: 'ЗА-ЩИ-ТА', phonetic: 'ZA-SHCHI-TA', translation: 'Protection' },
    { id: 'm106', cyrillic: 'РА-БО-ТА', phonetic: 'RA-BO-TA', translation: 'Work' },
    { id: 'm107', cyrillic: 'ЗА-БО-ТА', phonetic: 'ZA-BO-TA', translation: 'Care' },
    { id: 'm108', cyrillic: 'О-ХО-ТА', phonetic: 'O-KHO-TA', translation: 'Hunting' },
    { id: 'm109', cyrillic: 'СУБ-БО-ТА', phonetic: 'SUB-BO-TA', translation: 'Saturday' },
    { id: 'm110', cyrillic: 'О-ПЛА-ТА', phonetic: 'O-PLA-TA', translation: 'Payment' },
    { id: 'm111', cyrillic: 'ПА-ЛА-ТА', phonetic: 'PA-LA-TA', translation: 'Chamber' },
    { id: 'm112', cyrillic: 'МО-НЕ-ТА', phonetic: 'MO-NE-TA', translation: 'Coin' },
    { id: 'm113', cyrillic: 'ГА-ЗЕ-ТА', phonetic: 'GA-ZE-TA', translation: 'Newspaper' },
    { id: 'm114', cyrillic: 'КОН-ФЕ-ТА', phonetic: 'KON-FE-TA', translation: 'Candy' },
    { id: 'm115', cyrillic: 'КА-РЕ-ТА', phonetic: 'KA-RE-TA', translation: 'Carriage' },
    { id: 'm116', cyrillic: 'ПО-Э-ЗИ-Я', phonetic: 'PO-E-ZI-YA', translation: 'Poetry' },
    { id: 'm117', cyrillic: 'ТЕ-О-РИ-Я', phonetic: 'TE-O-RI-YA', translation: 'Theory' },
    { id: 'm118', cyrillic: 'И-СТО-РИ-Я', phonetic: 'I-STO-RI-YA', translation: 'History' },
    { id: 'm119', cyrillic: 'Э-НЕР-ГИ-Я', phonetic: 'E-NER-GI-YA', translation: 'Energy' },
    { id: 'm120', cyrillic: 'АР-МИ-Я', phonetic: 'AR-MI-YA', translation: 'Army' },
    { id: 'm121', cyrillic: 'ЛИ-НИ-Я', phonetic: 'LI-NI-YA', translation: 'Line' },
    { id: 'm122', cyrillic: 'СЕ-РИ-Я', phonetic: 'SE-RI-YA', translation: 'Series' },
    { id: 'm123', cyrillic: 'МА-ГИ-Я', phonetic: 'MA-GI-YA', translation: 'Magic' },
    { id: 'm124', cyrillic: 'ХИ-МИ-Я', phonetic: 'KHI-MI-YA', translation: 'Chemistry' },
    { id: 'm125', cyrillic: 'ФИ-ЗИ-КА', phonetic: 'FI-ZI-KA', translation: 'Physics' },
    { id: 'm126', cyrillic: 'ЛО-ГИ-КА', phonetic: 'LO-GI-KA', translation: 'Logic' },
    { id: 'm127', cyrillic: 'ОП-ТИ-КА', phonetic: 'OP-TI-KA', translation: 'Optics' },
    { id: 'm128', cyrillic: 'ПО-ЛИ-ТИ-КА', phonetic: 'PO-LI-TI-KA', translation: 'Politics' },
    { id: 'm129', cyrillic: 'ТАК-ТИ-КА', phonetic: 'TAK-TI-KA', translation: 'Tactics' },
    { id: 'm130', cyrillic: 'ТЕХ-НИ-КА', phonetic: 'TEKH-NI-KA', translation: 'Technique' },
    { id: 'm131', cyrillic: 'КРИ-ТИ-КА', phonetic: 'KRI-TI-KA', translation: 'Criticism' },
    { id: 'm132', cyrillic: 'ПРАК-ТИ-КА', phonetic: 'PRAK-TI-KA', translation: 'Practice' },
    { id: 'm133', cyrillic: 'Э-ТИ-КА', phonetic: 'E-TI-KA', translation: 'Ethics' },
    { id: 'm134', cyrillic: 'А-КУ-СТИ-КА', phonetic: 'A-KU-STI-KA', translation: 'Acoustics' },
    { id: 'm135', cyrillic: 'ПО-Э-ЗИ-Я', phonetic: 'PO-E-ZI-YA', translation: 'Verse' },
    { id: 'm136', cyrillic: 'СУДЬ-БА', phonetic: 'SUD\'-BA', translation: 'Fate' },
    { id: 'm137', cyrillic: 'БОРЬ-БА', phonetic: 'BOR\'-BA', translation: 'Struggle' },
    { id: 'm138', cyrillic: 'СЛУЖ-БА', phonetic: 'SLUZH-BA', translation: 'Service' },
    { id: 'm139', cyrillic: 'У-САДЬ-БА', phonetic: 'U-SAD\'-BA', translation: 'Estate' },
    { id: 'm140', cyrillic: 'СВАДЬ-БА', phonetic: 'SVAD\'-BA', translation: 'Wedding' },
    { id: 'm141', cyrillic: 'ПРО-ШЬ-БА', phonetic: 'PROSH-BA', translation: 'Request' },
    { id: 'm142', cyrillic: 'ХОДЬ-БА', phonetic: 'KHOD\'-BA', translation: 'Walking' },
    { id: 'm143', cyrillic: 'СТРЕЛЬ-БА', phonetic: 'STREL\'-BA', translation: 'Shooting' },
    { id: 'm144', cyrillic: 'У-ЧЕ-БА', phonetic: 'U-CHE-BA', translation: 'Studies' },
    { id: 'm145', cyrillic: 'СУДЬ-Я', phonetic: 'SUD\'-YA', translation: 'Judge' },
    { id: 'm146', cyrillic: 'ЛА-ДЬЯ', phonetic: 'LA-D\'YA', translation: 'Rook / Boat' },
    { id: 'm147', cyrillic: 'СТАТЬ-Я', phonetic: 'STAT\'-YA', translation: 'Article' },
    { id: 'm148', cyrillic: 'ПЛА-ТЬЕ', phonetic: 'PLA-T\'YE', translation: 'Dress' },
    { id: 'm149', cyrillic: 'ЖИ-ЛЬЕ', phonetic: 'ZHI-L\'YE', translation: 'Housing' },
    { id: 'm150', cyrillic: 'БЕ-ЛЬЕ', phonetic: 'BE-L\'YE', translation: 'Linen' },
    { id: 'm151', cyrillic: 'КО-ПЬЕ', phonetic: 'KO-P\'YE', translation: 'Spear' },
    { id: 'm152', cyrillic: 'ПЕР-ЬЯ', phonetic: 'PER\'-YA', translation: 'Feathers' },
    { id: 'm153', cyrillic: 'КРЫ-ЛЬЯ', phonetic: 'KRY-L\'YA', translation: 'Wings' },
    { id: 'm154', cyrillic: 'БРА-ТЬЯ', phonetic: 'BRA-T\'YA', translation: 'Brothers' },
    { id: 'm155', cyrillic: 'ЛИ-СТЬЯ', phonetic: 'LI-ST\'YA', translation: 'Leaves' },
    { id: 'm156', cyrillic: 'ДЕР-ЕВ-ЬЯ', phonetic: 'DER-EV-YA', translation: 'Trees' },
    { id: 'm157', cyrillic: 'ДРУ-ЗЬЯ', phonetic: 'DRU-Z\'YA', translation: 'Friends' },
    { id: 'm158', cyrillic: 'СУ-ДЬИ', phonetic: 'SU-D\'I', translation: 'Judges' },
    { id: 'm159', cyrillic: 'КНЯ-ЗЬЯ', phonetic: 'KNYA-Z\'YA', translation: 'Princes' },
    { id: 'm160', cyrillic: 'ГО-СТЬЯ', phonetic: 'GO-ST\'YA', translation: 'Guest (female)' },
    { id: 'm161', cyrillic: 'ЗДОР-ОВ-ЬЕ', phonetic: 'ZDOR-OV-YE', translation: 'Health' },
    { id: 'm162', cyrillic: 'ПРИ-МЕР', phonetic: 'PRI-MER', translation: 'Example' },
    { id: 'm163', cyrillic: 'РАЗ-МЕР', phonetic: 'RAZ-MER', translation: 'Size' },
    { id: 'm164', cyrillic: 'ОБ-МЕН', phonetic: 'OB-MEN', translation: 'Exchange' },
    { id: 'm165', cyrillic: 'ОБ-МАН', phonetic: 'OB-MAN', translation: 'Deception' },
    { id: 'm166', cyrillic: 'ТУ-МАН', phonetic: 'TU-MAN', translation: 'Fog' },
    { id: 'm167', cyrillic: 'О-КЕ-АН', phonetic: 'O-KE-AN', translation: 'Ocean' },
    { id: 'm168', cyrillic: 'ВУЛ-КАН', phonetic: 'VUL-KAN', translation: 'Volcano' },
    { id: 'm169', cyrillic: 'ФОН-ТАН', phonetic: 'FON-TAN', translation: 'Fountain' },
    { id: 'm170', cyrillic: 'Э-КРАН', phonetic: 'E-KRAN', translation: 'Screen' },
    { id: 'm171', cyrillic: 'ОР-ГАН', phonetic: 'OR-GAN', translation: 'Organ' },
    { id: 'm172', cyrillic: 'ДИ-ВАН', phonetic: 'DI-VAN', translation: 'Sofa' },
    { id: 'm173', cyrillic: 'СТА-КАН', phonetic: 'STA-KAN', translation: 'Glass' },
    { id: 'm174', cyrillic: 'КАР-МАН', phonetic: 'KAR-MAN', translation: 'Pocket' },
    { id: 'm175', cyrillic: 'ЧЕ-МО-ДАН', phonetic: 'CHE-MO-DAN', translation: 'Suitcase' },
    { id: 'm176', cyrillic: 'КА-ПИ-ТАН', phonetic: 'KA-PI-TAN', translation: 'Captain' },
    { id: 'm177', cyrillic: 'У-РА-ГАН', phonetic: 'U-RA-GAN', translation: 'Hurricane' },
    { id: 'm178', cyrillic: 'ВЕ-ТЕ-РАН', phonetic: 'VE-TE-RAN', translation: 'Veteran' },
    { id: 'm179', cyrillic: 'РЕ-ГИ-ОН', phonetic: 'RE-GI-ON', translation: 'Region' },
    { id: 'm180', cyrillic: 'СЕ-ЗОН', phonetic: 'SE-ZON', translation: 'Season' },
    { id: 'm181', cyrillic: 'СА-ЛОН', phonetic: 'SA-LON', translation: 'Salon' },
    { id: 'm182', cyrillic: 'ВА-ГОН', phonetic: 'VA-GON', translation: 'Wagon / Car' },
    { id: 'm183', cyrillic: 'БА-ЛОН', phonetic: 'BA-LON', translation: 'Cylinder' },
    { id: 'm184', cyrillic: 'РА-ЙОН', phonetic: 'RA-YON', translation: 'District' },
    { id: 'm185', cyrillic: 'БЕТ-ОН', phonetic: 'BET-ON', translation: 'Concrete' },
    { id: 'm186', cyrillic: 'БУ-ЛЬОН', phonetic: 'BU-L\'YON', translation: 'Broth' },
    { id: 'm187', cyrillic: 'КАН-ЬОН', phonetic: 'KAN-YON', translation: 'Canyon' },
    { id: 'm188', cyrillic: 'ЧЕМ-ПИ-ОН', phonetic: 'CHEM-PI-ON', translation: 'Champion' },
    { id: 'm189', cyrillic: 'СТА-ДИ-ОН', phonetic: 'STA-DI-ON', translation: 'Stadium' },
    { id: 'm190', cyrillic: 'МИЛ-ЛИ-ОН', phonetic: 'MIL-LI-ON', translation: 'Million' },
    { id: 'm191', cyrillic: 'БА-ТА-ЛЬОН', phonetic: 'BA-TA-L\'YON', translation: 'Battalion' },
    { id: 'm192', cyrillic: 'ПА-ВИ-ЛЬОН', phonetic: 'PA-VI-L\'YON', translation: 'Pavilion' },
    { id: 'm193', cyrillic: 'МЕД-А-ЛЬОН', phonetic: 'MED-A-L\'YON', translation: 'Locket' },
    { id: 'm194', cyrillic: 'ПО-ЧТА-ЛЬОН', phonetic: 'PO-CHTA-L\'YON', translation: 'Postman' },
    { id: 'm195', cyrillic: 'Э-ШЕ-ЛОН', phonetic: 'E-SHE-LON', translation: 'Echelon' },
    { id: 'm196', cyrillic: 'ОР-КЕСТР', phonetic: 'OR-KESTR', translation: 'Orchestra' },
    { id: 'm197', cyrillic: 'ТЕ-КСТ', phonetic: 'TE-KST', translation: 'Text' },
    { id: 'm198', cyrillic: 'ТЕСТ', phonetic: 'TEST', translation: 'Test' },
    { id: 'm199', cyrillic: 'ГЕ-РОЙ', phonetic: 'GE-ROY', translation: 'Hero' },
    { id: 'm200', cyrillic: 'ПРО-БОЙ', phonetic: 'PRO-BOY', translation: 'Breakthrough' }
  ],
  hard: [
    { id: 'h1', cyrillic: 'БА-БУШ-КА', phonetic: 'BA-BUSH-KA', translation: 'Grandmother' },
    { id: 'h2', cyrillic: 'РЕ-СТО-РАН', phonetic: 'RE-STO-RAN', translation: 'Restaurant' },
    { id: 'h3', cyrillic: 'ЗДРАВ-СТВУЙ-ТЕ', phonetic: 'ZDRAV-STVUY-TE', translation: 'Hello' },
    { id: 'h4', cyrillic: 'ОБЪ-ЕКТ', phonetic: "OB'YEKT", translation: 'Object' },
    { id: 'h5', cyrillic: 'СУБЪ-ЕКТ', phonetic: "SUB'YEKT", translation: 'Subject' },
    { id: 'h6', cyrillic: 'ЭК-РАН', phonetic: 'EK-RAN', translation: 'Screen' },
    { id: 'h7', cyrillic: 'ЩИТ', phonetic: 'SHCHIT', translation: 'Shield' },
    { id: 'h8', cyrillic: 'ЮГ', phonetic: 'YUG', translation: 'South' },
    { id: 'h9', cyrillic: 'ПРЕД-ПРИ-Я-ТИ-Е', phonetic: 'PRED-PRI-YA-TI-YE', translation: 'Enterprise' },
    { id: 'h10', cyrillic: 'ДО-СТО-ПРИ-МЕ-ЧА-ТЕЛЬ-НОСТЬ', phonetic: 'DO-STO-PRI-ME-CHA-TEL\'-NOST\'', translation: 'Attraction / Sight' },
    { id: 'h11', cyrillic: 'БЛА-ГО-ДАР-НОСТЬ', phonetic: 'BLA-GO-DAR-NOST\'', translation: 'Gratitude' },
    { id: 'h12', cyrillic: 'У-ДО-ВОЛЬ-СТВИ-Е', phonetic: 'U-DO-VOL\'-STVI-YE', translation: 'Pleasure' },
    { id: 'h13', cyrillic: 'ПРЕ-КРАС-НО', phonetic: 'PRE-KRAS-NO', translation: 'Wonderful' },
    { id: 'h14', cyrillic: 'ПУ-ТЕ-ШЕ-СТВИ-Е', phonetic: 'PU-TE-SHE-STVI-YE', translation: 'Journey / Travel' },
    { id: 'h15', cyrillic: 'ВДОХ-НО-ВЕ-НИ-Е', phonetic: 'VDOKH-NO-VE-NI-YE', translation: 'Inspiration' },
    { id: 'h16', cyrillic: 'СНЕ-ГО-ПАД', phonetic: 'SNE-GO-PAD', translation: 'Snowfall' },
    { id: 'h17', cyrillic: 'ЗЕ-МЛЕ-ТРЯ-СЕ-НИ-Е', phonetic: 'ZE-MLE-TRYA-SE-NI-YE', translation: 'Earthquake' },
    { id: 'h18', cyrillic: 'ПРО-ИЗ-ВОД-СТВО', phonetic: 'PRO-IZ-VOD-STVO', translation: 'Production' },
    { id: 'h19', cyrillic: 'СТРО-И-ТЕЛЬ-СТВО', phonetic: 'STRO-I-TEL\'-STVO', translation: 'Construction' },
    { id: 'h20', cyrillic: 'ПРА-ВИ-ТЕЛЬ-СТВО', phonetic: 'PRA-VI-TEL\'-STVO', translation: 'Government' },
    { id: 'h21', cyrillic: 'БЕ-ЗО-ПАС-НОСТЬ', phonetic: 'BE-ZO-PAS-NOST\'', translation: 'Safety' },
    { id: 'h22', cyrillic: 'СНЕ-ГУ-РОЧ-КА', phonetic: 'SNE-GU-ROCH-KA', translation: 'Snow Maiden' },
    { id: 'h23', cyrillic: 'ПРИ-КЛЮ-ЧЕ-НИ-Е', phonetic: 'PRI-KLYU-CHE-NI-YE', translation: 'Adventure' },
    { id: 'h24', cyrillic: 'ВО-ОБ-РА-ЖЕ-НИ-Е', phonetic: 'VO-OB-RA-ZHE-NI-YE', translation: 'Imagination' },
    { id: 'h25', cyrillic: 'ВЕ-ЛИ-КО-ЛЕП-НО', phonetic: 'VE-LI-KO-LEP-NO', translation: 'Magnificent' },
    { id: 'h26', cyrillic: 'ОБ-ЩЕ-ЖИ-ТИ-Е', phonetic: 'OB-SHCHE-ZHI-TI-YE', translation: 'Dormitory' },
    { id: 'h27', cyrillic: 'ПЕ-РЕ-ВОД-ЧИК', phonetic: 'PE-RE-VOD-CHIK', translation: 'Translator' },
    { id: 'h28', cyrillic: 'Э-ЛЕК-ТРО-НИ-КА', phonetic: 'E-LEK-TRO-NI-KA', translation: 'Electronics' },
    { id: 'h29', cyrillic: 'АВ-ТО-МО-БИЛЬ', phonetic: 'AV-TO-MO-BIL\'', translation: 'Automobile' },
    { id: 'h30', cyrillic: 'ПРО-ГРАМ-МИ-РО-ВА-НИ-Е', phonetic: 'PRO-GRAM-MI-RO-VA-NI-YE', translation: 'Programming' },
    { id: 'h31', cyrillic: 'ТЕ-ЛЕ-ФОН', phonetic: 'TE-LE-FON', translation: 'Telephone' },
    { id: 'h32', cyrillic: 'ТЕ-ЛЕ-ВИ-ЗОР', phonetic: 'TE-LE-VI-ZOR', translation: 'Television' },
    { id: 'h33', cyrillic: 'ВЕ-ЛО-СИ-ПЕД', phonetic: 'VE-LO-SI-PED', translation: 'Bicycle' },
    { id: 'h34', cyrillic: 'ФО-ТО-ГРА-ФИ-Я', phonetic: 'FO-TO-GRA-FI-YA', translation: 'Photograph' },
    { id: 'h35', cyrillic: 'ЭК-СКУР-СИ-Я', phonetic: 'EK-SKUR-SI-YA', translation: 'Excursion' },
    { id: 'h36', cyrillic: 'ИН-ФОР-МА-ЦИ-Я', phonetic: 'IN-FOR-MA-TSI-YA', translation: 'Information' },
    { id: 'h37', cyrillic: 'КУЛЬ-ТУ-РА', phonetic: 'KUL\'-TU-RA', translation: 'Culture' },
    { id: 'h38', cyrillic: 'ЛИ-ТЕ-РА-ТУ-РА', phonetic: 'LI-TE-RA-TU-RA', translation: 'Literature' },
    { id: 'h39', cyrillic: 'АР-ХИ-ТЕК-ТУ-РА', phonetic: 'AR-KHI-TEK-TU-RA', translation: 'Architecture' },
    { id: 'h40', cyrillic: 'У-НИ-ВЕР-СИ-ТЕТ', phonetic: 'U-NI-VER-SI-TET', translation: 'University' },
    { id: 'h41', cyrillic: 'БИБ-ЛИ-О-ТЕ-КА', phonetic: 'BIB-LI-O-TE-KA', translation: 'Library' },
    { id: 'h42', cyrillic: 'ГОС-У-ДАР-СТВО', phonetic: 'GOS-U-DAR-STVO', translation: 'State / Nation' },
    { id: 'h43', cyrillic: 'ПРО-ФЕС-СОР', phonetic: 'PRO-FES-SOR', translation: 'Professor' },
    { id: 'h44', cyrillic: 'ИН-ЖЕ-НЕР', phonetic: 'IN-ZHE-NER', translation: 'Engineer' },
    { id: 'h45', cyrillic: 'ХУ-ДОЖ-НИК', phonetic: 'KHU-DOZH-NIK', translation: 'Artist' },
    { id: 'h46', cyrillic: 'МУ-ЗЫ-КАНТ', phonetic: 'MU-ZY-KANT', translation: 'Musician' },
    { id: 'h47', cyrillic: 'СМЕРТЬ', phonetic: 'SMERT\'', translation: 'Death' },
    { id: 'h48', cyrillic: 'ЖИЗНЬ', phonetic: 'ZHIZN\'', translation: 'Life' },
    { id: 'h49', cyrillic: 'СЧА-СТЬЕ', phonetic: 'SCHA-ST\'YE', translation: 'Happiness' },
    { id: 'h50', cyrillic: 'ЗДО-РО-ВЬЕ', phonetic: 'ZDO-RO-V\'YE', translation: 'Health' },
    { id: 'h51', cyrillic: 'УС-ПЕХ', phonetic: 'US-PEKH', translation: 'Success' },
    { id: 'h52', cyrillic: 'ЛЮ-БОВЬ', phonetic: 'LYU-BOV\'', translation: 'Love' },
    { id: 'h53', cyrillic: 'ДРУЖ-БА', phonetic: 'DRUZH-BA', translation: 'Friendship' },
    { id: 'h54', cyrillic: 'СЕМЬ-Я', phonetic: 'SEM\'-YA', translation: 'Family' },
    { id: 'h55', cyrillic: 'ЧЕ-ЛО-ВЕК', phonetic: 'CHE-LO-VEK', translation: 'Person / Human' },
    { id: 'h56', cyrillic: 'РЕ-БЕ-НОК', phonetic: 'RE-BE-NOK', translation: 'Child' },
    { id: 'h57', cyrillic: 'ВЗРОС-ЛЫЙ', phonetic: 'VZROS-LYY', translation: 'Adult' },
    { id: 'h58', cyrillic: 'РО-ДИ-ТЕ-ЛИ', phonetic: 'RO-DI-TE-LI', translation: 'Parents' },
    { id: 'h59', cyrillic: 'У-ЧИ-ТЕЛЬ', phonetic: 'U-CHI-TEL\'', translation: 'Teacher' },
    { id: 'h60', cyrillic: 'У-ЧЕ-НИК', phonetic: 'U-CHE-NIK', translation: 'Student' },
    { id: 'h61', cyrillic: 'ШКОЛЬ-НИК', phonetic: 'SHKOL\'-NIK', translation: 'Schoolboy' },
    { id: 'h62', cyrillic: 'ПАС-СА-ЖИР', phonetic: 'PAS-SA-ZHIR', translation: 'Passenger' },
    { id: 'h63', cyrillic: 'ВО-ДИ-ТЕЛЬ', phonetic: 'VO-DI-TEL\'', translation: 'Driver' },
    { id: 'h64', cyrillic: 'ПО-КУ-ПА-ТЕЛЬ', phonetic: 'PO-KU-PA-TEL\'', translation: 'Buyer' },
    { id: 'h65', cyrillic: 'ПРО-ДА-ВЕЦ', phonetic: 'PRO-DA-VETS', translation: 'Seller' },
    { id: 'h66', cyrillic: 'ВРАЧ', phonetic: 'VRACH', translation: 'Doctor' },
    { id: 'h67', cyrillic: 'ПО-ЛИ-ЦЕЙ-СКИЙ', phonetic: 'PO-LI-TSEY-SKIY', translation: 'Police officer' },
    { id: 'h68', cyrillic: 'ПО-ЖАР-НЫЙ', phonetic: 'PO-ZHAR-NYY', translation: 'Firefighter' },
    { id: 'h69', cyrillic: 'ВО-ЕН-НЫЙ', phonetic: 'VO-YEN-NYY', translation: 'Military officer' },
    { id: 'h70', cyrillic: 'Ю-РИСТ', phonetic: 'YU-RIST', translation: 'Lawyer' },
    { id: 'h71', cyrillic: 'Э-КО-НО-МИСТ', phonetic: 'E-KO-NO-MIST', translation: 'Economist' },
    { id: 'h72', cyrillic: 'ЖУР-НА-ЛИСТ', phonetic: 'ZHUR-NA-LIST', translation: 'Journalist' },
    { id: 'h73', cyrillic: 'ПИ-СА-ТЕЛЬ', phonetic: 'PI-SA-TEL\'', translation: 'Writer' },
    { id: 'h74', cyrillic: 'ПО-ЭТ', phonetic: 'PO-ET', translation: 'Poet' },
    { id: 'h75', cyrillic: 'АР-ТИСТ', phonetic: 'AR-TIST', translation: 'Artist / Actor' },
    { id: 'h76', cyrillic: 'СПОРТС-МЕН', phonetic: 'SPORTS-MEN', translation: 'Athlete' },
    { id: 'h77', cyrillic: 'ПЕ-КАРЬ', phonetic: 'PE-KAR\'', translation: 'Baker' },
    { id: 'h78', cyrillic: 'СТРО-И-ТЕЛЬ', phonetic: 'STRO-I-TEL\'', translation: 'Builder' },
    { id: 'h79', cyrillic: 'СА-ДОВ-НИК', phonetic: 'SA-DOV-NIK', translation: 'Gardener' },
    { id: 'h80', cyrillic: 'ПА-РИК-МА-ХЕР', phonetic: 'PA-RIK-MA-KHER', translation: 'Hairdresser' },
    { id: 'h81', cyrillic: 'О-ФИ-ЦИ-АНТ', phonetic: 'O-FI-TSI-ANT', translation: 'Waiter' },
    { id: 'h82', cyrillic: 'КУ-РЬЕР', phonetic: 'KU-R\'YER', translation: 'Courier' },
    { id: 'h83', cyrillic: 'ШО-ФЕР', phonetic: 'SHO-FER', translation: 'Chauffeur' },
    { id: 'h84', cyrillic: 'ЛЁТ-ЧИК', phonetic: 'LYOT-CHIK', translation: 'Pilot' },
    { id: 'h85', cyrillic: 'МАТ-РОС', phonetic: 'MAT-ROS', translation: 'Sailor' },
    { id: 'h86', cyrillic: 'РЫ-БАК', phonetic: 'RY-BAK', translation: 'Fisherman' },
    { id: 'h87', cyrillic: 'ФЕР-МЕР', phonetic: 'FER-MER', translation: 'Farmer' },
    { id: 'h88', cyrillic: 'ШАХ-ТЁР', phonetic: 'SHAKH-TYOR', translation: 'Miner' },
    { id: 'h89', cyrillic: 'У-ЧЁ-НЫЙ', phonetic: 'U-CHYO-NYY', translation: 'Scientist' },
    { id: 'h90', cyrillic: 'АС-ТРО-НАВТ', phonetic: 'AS-TRO-NAVT', translation: 'Astronaut' },
    { id: 'h91', cyrillic: 'Э-КО-ЛОГ', phonetic: 'E-KO-LOG', translation: 'Ecologist' },
    { id: 'h92', cyrillic: 'БИ-О-ЛОГ', phonetic: 'BI-O-LOG', translation: 'Biologist' },
    { id: 'h93', cyrillic: 'ХИ-МИК', phonetic: 'KHI-MIK', translation: 'Chemist' },
    { id: 'h94', cyrillic: 'ФИ-ЗИК', phonetic: 'FI-ZIK', translation: 'Physicist' },
    { id: 'h95', cyrillic: 'МА-ТЕ-МА-ТИК', phonetic: 'MA-TE-MA-TIK', translation: 'Mathematician' },
    { id: 'h96', cyrillic: 'ИС-КУС-СТВО', phonetic: 'IS-KUS-STVO', translation: 'Art' },
    { id: 'h97', cyrillic: 'ПРИ-РО-ДА', phonetic: 'PRI-RO-DA', translation: 'Nature' },
    { id: 'h98', cyrillic: 'ОК-Е-АН', phonetic: 'OK-E-AN', translation: 'Ocean' },
    { id: 'h99', cyrillic: 'КОС-МОС', phonetic: 'KOS-MOS', translation: 'Space / Cosmos' },
    { id: 'h100', cyrillic: 'ГА-ЛАК-ТИ-КА', phonetic: 'GA-LAK-TI-KA', translation: 'Galaxy' },
    // 100 NEW HARD EXAMPLES (h101 - h200)
    { id: 'h101', cyrillic: 'ГО-СУ-ДАР-СТВЕН-НОСТЬ', phonetic: 'GOS-U-DAR-STVEN-NOST\'', translation: 'Statehood' },
    { id: 'h102', cyrillic: 'НЕ-ЗА-ВИ-СИ-МОСТЬ', phonetic: 'NE-ZA-VI-SI-MOST\'', translation: 'Independence' },
    { id: 'h103', cyrillic: 'О-ТВЕТ-СТВЕН-НОСТЬ', phonetic: 'O-TVET-STVEN-NOST\'', translation: 'Responsibility' },
    { id: 'h104', cyrillic: 'СПРА-ВЕД-ЛИ-ВОСТЬ', phonetic: 'SPRA-VED-LI-VOST\'', translation: 'Justice' },
    { id: 'h105', cyrillic: 'ДЕ-МО-КРА-ТИ-Я', phonetic: 'DE-MO-KRA-TI-YA', translation: 'Democracy' },
    { id: 'h106', cyrillic: 'ЦИ-ВИ-ЛИ-ЗА-ЦИ-Я', phonetic: 'TSI-VI-LI-ZA-TSI-YA', translation: 'Civilization' },
    { id: 'h107', cyrillic: 'Э-КО-НО-МИ-КА', phonetic: 'E-KO-NO-MI-KA', translation: 'Economy' },
    { id: 'h108', cyrillic: 'ПРО-МЫШ-ЛЕН-НОСТЬ', phonetic: 'PRO-MYSH-LEN-NOST\'', translation: 'Industry' },
    { id: 'h109', cyrillic: 'СЕЛЬ-СКО-Е ХО-ЗЯЙ-СТВО', phonetic: 'SEL\'-SKO-YE KHO-ZYAY-STVO', translation: 'Agriculture' },
    { id: 'h110', cyrillic: 'ЗА-КО-НО-ДА-ТЕЛЬ-СТВО', phonetic: 'ZA-KO-NO-DA-TEL\'-STVO', translation: 'Legislation' },
    { id: 'h111', cyrillic: 'СУ-ДО-ПРО-ИЗ-ВОД-СТВО', phonetic: 'SU-DO-PRO-IZ-VOD-STVO', translation: 'Legal proceedings' },
    { id: 'h112', cyrillic: 'ЗДРА-ВО-ОХ-РА-НЕ-НИ-Е', phonetic: 'ZDRA-VO-OKH-RA-NE-NI-YE', translation: 'Healthcare' },
    { id: 'h113', cyrillic: 'ОБ-РА-ЗО-ВА-НИ-Е', phonetic: 'OB-RA-ZO-VA-NI-YE', translation: 'Education' },
    { id: 'h114', cyrillic: 'ПРО-СВЕ-ЩЕ-НИ-Е', phonetic: 'PRO-SVE-SHCHE-NI-YE', translation: 'Enlightenment' },
    { id: 'h115', cyrillic: 'БЛА-ГО-У-СТРОЙ-СТВО', phonetic: 'BLA-GO-U-STROY-STVO', translation: 'Landscaping / Amenity' },
    { id: 'h116', cyrillic: 'ГРА-ДО-СТРО-И-ТЕЛЬ-СТВО', phonetic: 'GRA-DO-STRO-I-TEL\'-STVO', translation: 'Urban planning' },
    { id: 'h117', cyrillic: 'А-РХИ-ТЕК-ТУ-РА', phonetic: 'AR-KHI-TEK-TU-RA', translation: 'Architecture' },
    { id: 'h118', cyrillic: 'РЕ-КОН-СТРУК-ЦИ-Я', phonetic: 'RE-KON-STRUK-TSI-YA', translation: 'Reconstruction' },
    { id: 'h119', cyrillic: 'МО-ДЕР-НИ-ЗА-ЦИ-Я', phonetic: 'MO-DER-NI-ZA-TSI-YA', translation: 'Modernization' },
    { id: 'h120', cyrillic: 'О-ПТИ-МИ-ЗА-ЦИ-Я', phonetic: 'O-PTI-MI-ZA-TSI-YA', translation: 'Optimization' },
    { id: 'h121', cyrillic: 'АВ-ТО-МА-ТИ-ЗА-ЦИ-Я', phonetic: 'AV-TO-MA-TI-ZA-TSI-YA', translation: 'Automation' },
    { id: 'h122', cyrillic: 'РО-БО-ТО-ТЕХ-НИ-КА', phonetic: 'RO-BO-TO-TEKH-NI-KA', translation: 'Robotics' },
    { id: 'h123', cyrillic: 'КИ-БЕР-НЕ-ТИ-КА', phonetic: 'KI-BER-NE-TI-KA', translation: 'Cybernetics' },
    { id: 'h124', cyrillic: 'БИ-О-ТЕХ-НО-ЛО-ГИ-Я', phonetic: 'BI-O-TEKH-NO-LO-GI-YA', translation: 'Biotechnology' },
    { id: 'h125', cyrillic: 'НА-НО-ТЕХ-НО-ЛО-ГИ-Я', phonetic: 'NA-NO-TEKH-NO-LO-GI-YA', translation: 'Nanotechnology' },
    { id: 'h126', cyrillic: 'МИК-РО-Э-ЛЕК-ТРО-НИ-КА', phonetic: 'MIK-RO-E-LEK-TRO-NI-KA', translation: 'Microelectronics' },
    { id: 'h127', cyrillic: 'ТЕ-ЛЕ-КОМ-МУ-НИ-КА-ЦИ-Я', phonetic: 'TE-LE-KOM-MU-NI-KA-TSI-YA', translation: 'Telecommunication' },
    { id: 'h128', cyrillic: 'РА-ДИ-О-Э-ЛЕК-ТРО-НИ-КА', phonetic: 'RA-DI-O-E-LEK-TRO-NI-KA', translation: 'Radio electronics' },
    { id: 'h129', cyrillic: 'А-С-ТРО-ФИ-ЗИ-КА', phonetic: 'AS-TRO-FI-ZI-KA', translation: 'Astrophysics' },
    { id: 'h130', cyrillic: 'КОС-МО-НАВ-ТИ-КА', phonetic: 'KOS-MO-NAV-TI-KA', translation: 'Cosmonautics' },
    { id: 'h131', cyrillic: 'А-ВИ-А-ЦИ-Я', phonetic: 'A-VI-A-TSI-YA', translation: 'Aviation' },
    { id: 'h132', cyrillic: 'СУ-ДО-СТРО-Е-НИ-Е', phonetic: 'SU-DO-STRO-YE-NI-YE', translation: 'Shipbuilding' },
    { id: 'h133', cyrillic: 'МА-ШИ-НО-СТРО-Е-НИ-Е', phonetic: 'MA-SHI-NO-STRO-YE-NI-YE', translation: 'Mechanical engineering' },
    { id: 'h134', cyrillic: 'МЕ-ТАЛ-ЛУР-ГИ-Я', phonetic: 'ME-TAL-LUR-GI-YA', translation: 'Metallurgy' },
    { id: 'h135', cyrillic: 'Э-НЕР-ГЕ-ТИ-КА', phonetic: 'E-NER-GE-TI-KA', translation: 'Power engineering' },
    { id: 'h136', cyrillic: 'ГИ-ДРО-Э-НЕР-ГЕ-ТИ-КА', phonetic: 'GI-DRO-E-NER-GE-TI-KA', translation: 'Hydroelectric power' },
    { id: 'h137', cyrillic: 'А-ТОМ-НА-Я Э-НЕР-ГИ-Я', phonetic: 'A-TOM-NA-YA E-NER-GI-YA', translation: 'Nuclear energy' },
    { id: 'h138', cyrillic: 'Э-КО-ЛО-ГИ-Я', phonetic: 'E-KO-LO-GI-YA', translation: 'Ecology' },
    { id: 'h139', cyrillic: 'МЕ-ТЕ-О-РО-ЛО-ГИ-Я', phonetic: 'ME-TE-O-RO-LO-GI-YA', translation: 'Meteorology' },
    { id: 'h140', cyrillic: 'КЛИ-МА-ТО-ЛО-ГИ-Я', phonetic: 'KLI-MA-TO-LO-GI-YA', translation: 'Climatology' },
    { id: 'h141', cyrillic: 'ГЕ-О-ЛО-ГИ-Я', phonetic: 'GE-O-LO-GI-YA', translation: 'Geology' },
    { id: 'h142', cyrillic: 'ГЕ-О-ГРА-ФИ-Я', phonetic: 'GE-O-GRA-FI-YA', translation: 'Geography' },
    { id: 'h143', cyrillic: 'КАР-ТО-ГРА-ФИ-Я', phonetic: 'KAR-TO-GRA-FI-YA', translation: 'Cartography' },
    { id: 'h144', cyrillic: 'О-КЕ-А-НО-ЛО-ГИ-Я', phonetic: 'O-KE-A-NO-LO-GI-YA', translation: 'Oceanology' },
    { id: 'h145', cyrillic: 'АР-ХЕ-О-ЛО-ГИ-Я', phonetic: 'AR-KHE-O-LO-GI-YA', translation: 'Archaeology' },
    { id: 'h146', cyrillic: 'ЭТ-НО-ГРА-ФИ-Я', phonetic: 'ET-NO-GRA-FI-YA', translation: 'Ethnography' },
    { id: 'h147', cyrillic: 'АН-ТРО-ПО-ЛО-ГИ-Я', phonetic: 'AN-TRO-PO-LO-GI-YA', translation: 'Anthropology' },
    { id: 'h148', cyrillic: 'СО-ЦИ-О-ЛО-ГИ-Я', phonetic: 'SO-TSI-O-LO-GI-YA', translation: 'Sociology' },
    { id: 'h149', cyrillic: 'ПСИ-ХО-ЛО-ГИ-Я', phonetic: 'PSI-KHO-LO-GI-YA', translation: 'Psychology' },
    { id: 'h150', cyrillic: 'ПЕ-ДА-ГО-ГИ-КА', phonetic: 'PE-DA-GO-GI-KA', translation: 'Pedagogy' },
    { id: 'h151', cyrillic: 'ФИ-ЛО-СО-ФИ-Я', phonetic: 'FI-LO-SO-FI-YA', translation: 'Philosophy' },
    { id: 'h152', cyrillic: 'ФИ-ЛО-ЛО-ГИ-Я', phonetic: 'FI-LO-LO-GI-YA', translation: 'Philology' },
    { id: 'h153', cyrillic: 'ЛИНГ-ВИ-СТИ-КА', phonetic: 'LING-VI-STI-KA', translation: 'Linguistics' },
    { id: 'h154', cyrillic: 'ГРАМ-МА-ТИ-КА', phonetic: 'GRAM-MA-TI-KA', translation: 'Grammar' },
    { id: 'h155', cyrillic: 'ФO-НЕ-ТИ-КА', phonetic: 'FO-NE-TI-KA', translation: 'Phonetics' },
    { id: 'h156', cyrillic: 'ЛЕК-СИ-КО-ЛО-ГИ-Я', phonetic: 'LEK-SI-KO-LO-GI-YA', translation: 'Lexicology' },
    { id: 'h157', cyrillic: 'СЕМ-АН-ТИ-КА', phonetic: 'SEM-AN-TI-KA', translation: 'Semantics' },
    { id: 'h158', cyrillic: 'СИН-ТАК-СИС', phonetic: 'SIN-TAK-SIS', translation: 'Syntax' },
    { id: 'h159', cyrillic: 'СТИ-ЛИ-СТИ-КА', phonetic: 'STI-LI-STI-KA', translation: 'Stylistics' },
    { id: 'h160', cyrillic: 'РИ-ТО-РИ-КА', phonetic: 'RI-TO-RI-KA', translation: 'Rhetoric' },
    { id: 'h161', cyrillic: 'ДЕ-КЛА-МА-ЦИ-Я', phonetic: 'DE-KLA-MA-TSI-YA', translation: 'Recitation' },
    { id: 'h162', cyrillic: 'ДРА-МА-ТУР-ГИ-Я', phonetic: 'DRA-MA-TUR-GI-YA', translation: 'Dramaturgy' },
    { id: 'h163', cyrillic: 'ХИ-РО-МАН-ТИ-Я', phonetic: 'KHI-RO-MAN-TI-YA', translation: 'Palmistry' },
    { id: 'h164', cyrillic: 'АС-ТРО-ЛО-ГИ-Я', phonetic: 'AS-TRO-LO-GI-YA', translation: 'Astrology' },
    { id: 'h165', cyrillic: 'МИ-ФО-ЛО-ГИ-Я', phonetic: 'MI-FO-LO-GI-YA', translation: 'Mythology' },
    { id: 'h166', cyrillic: 'ТЕ-О-ЛО-ГИ-Я', phonetic: 'TE-O-LO-GI-YA', translation: 'Theology' },
    { id: 'h167', cyrillic: 'РЕ-ЛИ-ГИ-О-ВЕ-ДЕ-НИ-Е', phonetic: 'RE-LI-GI-O-VE-DE-NI-YE', translation: 'Religious studies' },
    { id: 'h168', cyrillic: 'ИС-КУС-СТВО-ВЕ-ДЕ-НИ-Е', phonetic: 'IS-KUS-STVO-VE-DE-NI-YE', translation: 'Art history' },
    { id: 'h169', cyrillic: 'МУ-ЗЫ-КО-VE-ДЕ-НИ-Е', phonetic: 'MU-ZY-KO-VE-DE-NI-YE', translation: 'Musicology' },
    { id: 'h170', cyrillic: 'КИ-НО-ИС-КУС-СТВО', phonetic: 'KI-NO-IS-KUS-STVO', translation: 'Cinema art' },
    { id: 'h171', cyrillic: 'ХО-РЕ-О-ГРА-ФИ-Я', phonetic: 'KHO-RE-O-GRA-FI-YA', translation: 'Choreography' },
    { id: 'h172', cyrillic: 'СЦE-НО-ГРА-ФИ-Я', phonetic: 'STSE-NO-GRA-FI-YA', translation: 'Scenography' },
    { id: 'h173', cyrillic: 'СКУЛЬП-ТУ-РА', phonetic: 'SKUL\'-PTU-RA', translation: 'Sculpture' },
    { id: 'h174', cyrillic: 'ЖИ-ВО-ПИСЬ', phonetic: 'ZHI-VO-PIS\'', translation: 'Painting' },
    { id: 'h175', cyrillic: 'ГРА-ФИ-КА', phonetic: 'GRA-FI-KA', translation: 'Graphics' },
    { id: 'h176', cyrillic: 'ИЛ-ЛЮ-СТРА-ЦИ-Я', phonetic: 'IL-LYU-STRA-TSI-YA', translation: 'Illustration' },
    { id: 'h177', cyrillic: 'ДИ-ЗАЙН', phonetic: 'DI-ZAYN', translation: 'Design' },
    { id: 'h178', cyrillic: 'КАЛ-ЛИ-ГРА-ФИ-Я', phonetic: 'KAL-LI-GRA-FI-YA', translation: 'Calligraphy' },
    { id: 'h179', cyrillic: 'ПО-ЛИ-ГРА-ФИ-Я', phonetic: 'PO-LI-GRA-FI-YA', translation: 'Printing / Polygraphy' },
    { id: 'h180', cyrillic: 'ИЗ-ДА-ТЕЛЬ-СТВО', phonetic: 'IZ-DA-TEL\'-STVO', translation: 'Publishing house' },
    { id: 'h181', cyrillic: 'ЖУР-НА-ЛИ-СТИ-КА', phonetic: 'ZHUR-NA-LI-STI-KA', translation: 'Journalism' },
    { id: 'h182', cyrillic: 'ТЕ-ЛЕ-ВИ-ДЕ-НИ-Е', phonetic: 'TE-LE-VI-DE-NI-YE', translation: 'Television' },
    { id: 'h183', cyrillic: 'РА-ДИ-О-ВЕ-ЩА-НИ-Е', phonetic: 'RA-DI-O-VE-SHCHA-NI-YE', translation: 'Broadcasting' },
    { id: 'h184', cyrillic: 'ИН-ТЕР-НЕТ', phonetic: 'IN-TER-NET', translation: 'Internet' },
    { id: 'h185', cyrillic: 'СЕ-ТЕ-ВО-Е ОБ-ЩЕ-СТВО', phonetic: 'SE-TE-VO-YE OB-SHCHE-STVO', translation: 'Networked society' },
    { id: 'h186', cyrillic: 'КИ-БЕР-БЕ-ЗО-ПАС-НОСТЬ', phonetic: 'KI-BER-BE-ZO-PAS-NOST\'', translation: 'Cybersecurity' },
    { id: 'h187', cyrillic: 'КРИП-ТО-ГРА-ФИ-Я', phonetic: 'KRIP-TO-GRA-FI-YA', translation: 'Cryptography' },
    { id: 'h188', cyrillic: 'БЛОК-ЧЕЙН', phonetic: 'BLOK-CHEYN', translation: 'Blockchain' },
    { id: 'h189', cyrillic: 'И-СКУС-СТВЕН-НЫЙ ИН-ТЕЛ-ЛЕКТ', phonetic: 'IS-KUS-STVEN-NYY IN-TEL-LEKT', translation: 'Artificial Intelligence' },
    { id: 'h190', cyrillic: 'МА-ШИН-НО-Е О-БУ-ЧЕ-НИ-Е', phonetic: 'MA-SHIN-NO-YE O-BU-CHE-NI-YE', translation: 'Machine Learning' },
    { id: 'h191', cyrillic: 'НЕЙ-РО-СЕ-ТИ', phonetic: 'NEY-RO-SE-TI', translation: 'Neural Networks' },
    { id: 'h192', cyrillic: 'АЛ-ГО-РИТМ', phonetic: 'AL-GO-RITM', translation: 'Algorithm' },
    { id: 'h193', cyrillic: 'ВЫ-ЧИС-ЛЕ-НИ-Я', phonetic: 'VY-CHIS-LE-NI-YA', translation: 'Computations' },
    { id: 'h194', cyrillic: 'СУ-ПЕР-КОМ-ПЬЮ-ТЕР', phonetic: 'SU-PER-KOM-P\'YU-TER', translation: 'Supercomputer' },
    { id: 'h195', cyrillic: 'КВАН-ТО-ВА-Я МЕ-ХА-НИ-КА', phonetic: 'KVAN-TO-VA-YA ME-KHA-NI-KA', translation: 'Quantum Mechanics' },
    { id: 'h196', cyrillic: 'ТЕ-О-РИ-Я ОТ-НО-СИ-ТЕЛЬ-НО-СТИ', phonetic: 'TE-O-RI-YA OT-NO-SI-TEL\'-NO-STI', translation: 'Theory of Relativity' },
    { id: 'h197', cyrillic: 'ТЕР-МО-ДИ-НА-МИ-КА', phonetic: 'TER-MO-DI-NA-MI-KA', translation: 'Thermodynamics' },
    { id: 'h198', cyrillic: 'Э-ЛЕК-ТРО-МА-ГНЕ-ТИЗМ', phonetic: 'E-LEK-TRO-MA-GNE-TIZM', translation: 'Electromagnetism' },
    { id: 'h199', cyrillic: 'МИК-РО-БИ-О-ЛО-ГИ-Я', phonetic: 'MIK-RO-BI-O-LO-GI-YA', translation: 'Microbiology' },
    { id: 'h200', cyrillic: 'ГЕ-НЕ-ТИ-КА', phonetic: 'GE-NE-TI-KA', translation: 'Genetics' }
  ]
};

export function ReadingTrainer() {
  const [level, setLevel] = useState<ReadingLevel>('easy');
  const [currentIndex, setCurrentIndex] = useState(0);
  const [revealed, setRevealed] = useState(false);

  const currentList = READING_DATA[level];
  const item = currentList[currentIndex] || currentList[0];

  // Pick a random index when level changes or component mounts
  useEffect(() => {
    const list = READING_DATA[level];
    const randomIdx = Math.floor(Math.random() * list.length);
    setCurrentIndex(randomIdx);
    setRevealed(false);
  }, [level]);

  const handleNext = () => {
    setRevealed(false);
    let nextIdx = Math.floor(Math.random() * currentList.length);
    if (nextIdx === currentIndex && currentList.length > 1) {
      nextIdx = (currentIndex + 1) % currentList.length;
    }
    setCurrentIndex(nextIdx);
  };

  const handleLevelChange = (newLevel: ReadingLevel) => {
    setLevel(newLevel);
  };

  return (
    <div className="flex flex-col items-center p-8 bg-vintage-paper border-2 border-vintage-ink shadow-[4px_4px_0_0_#2C2A29] relative">
      {/* Level selector tabs */}
      <div className="flex gap-2 mb-8 w-full max-w-md">
        {(['easy', 'medium', 'hard'] as ReadingLevel[]).map((lvl) => (
          <button
            key={lvl}
            onClick={() => handleLevelChange(lvl)}
            className={clsx(
              "flex-1 py-2 font-mono text-xs font-bold uppercase tracking-wider border-2 border-vintage-ink transition-all cursor-pointer",
              level === lvl
                ? "bg-vintage-gold text-vintage-ink shadow-[2px_2px_0_0_#2C2A29]"
                : "bg-white text-vintage-ink/70 hover:bg-gray-100"
            )}
          >
            {lvl === 'easy' ? `Easy (${READING_DATA.easy.length})` : lvl === 'medium' ? `Medium (${READING_DATA.medium.length})` : `Hard (${READING_DATA.hard.length})`}
          </button>
        ))}
      </div>

      <h3 className="font-bold text-vintage-blue uppercase tracking-widest text-sm mb-2 text-center">
        Read the Cyrillic out loud
      </h3>
      <p className="font-serif text-sm italic text-vintage-ink/70 mb-8 text-center max-w-md">
        Sound out the syllables below, then click Reveal to check your pronunciation and translation.
      </p>

      {/* Main Cyrillic Card */}
      <div className="w-full max-w-md bg-white border-2 border-vintage-ink p-8 flex flex-col items-center justify-center mb-8 shadow-[4px_4px_0_0_#2C2A29]">
        <div className="text-5xl md:text-6xl font-serif font-bold text-vintage-ink tracking-widest mb-4 text-center">
          {item.cyrillic}
        </div>

        {/* Revealed Details */}
        {revealed && (
          <div className="mt-6 pt-6 border-t-2 border-vintage-ink border-dashed w-full text-center">
            <div className="text-2xl font-mono font-bold text-vintage-blue mb-1">
              [{item.phonetic}]
            </div>
            <div className="text-xl font-serif italic text-vintage-red mb-3">
              "{item.translation}"
            </div>
            <a 
              href={`https://en.wiktionary.org/wiki/${encodeURIComponent(item.cyrillic.replace(/[-'’]/g, '').toLowerCase())}#Russian`}
              target="_blank" 
              rel="noopener noreferrer"
              className="inline-block text-vintage-blue hover:text-vintage-red underline font-serif font-bold text-sm cursor-pointer"
            >
              View on Wiktionary &rarr;
            </a>
          </div>
        )}
      </div>

      {/* Controls */}
      {!revealed ? (
        <div className="w-full max-w-md flex gap-4">
          <button
            onClick={handleNext}
            className="flex-1 py-3 font-serif font-bold text-lg border-2 border-vintage-ink bg-white hover:bg-gray-100 transition-colors cursor-pointer"
          >
            Skip Word
          </button>
          <button
            onClick={() => setRevealed(true)}
            className="flex-1 py-3 font-serif font-bold text-lg border-2 border-vintage-ink shadow-[2px_2px_0_0_#2C2A29] bg-vintage-gold hover:bg-[#d4a849] transition-all active:translate-y-[2px] active:translate-x-[2px] active:shadow-none cursor-pointer flex items-center justify-center gap-2"
          >
            <Eye size={20} /> Reveal
          </button>
        </div>
      ) : (
        <div className="w-full max-w-md flex justify-between gap-4">
          <button
            onClick={handleNext}
            className="w-full py-3 bg-vintage-ink text-white font-serif font-bold text-xl hover:bg-gray-800 transition-colors cursor-pointer shadow-[4px_4px_0_0_#D9AD5B] flex items-center justify-center gap-2"
          >
            Next Word <ArrowRight size={24} />
          </button>
        </div>
      )}
    </div>
  );
}
